# Generated by Django 2.0.5 on 2018-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('s_class', models.IntegerField()),
                ('s_address', models.CharField(max_length=200)),
                ('s_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
