# Generated by Django 2.0.5 on 2018-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tab',
            name='s_phone',
            field=models.TextField(max_length=200),
        ),
    ]
