# Generated by Django 2.0.5 on 2018-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='cs_files'),
        ),
    ]
