# Generated by Django 2.0.5 on 2018-06-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0011_employee_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='csv_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='cs_files')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='file',
        ),
    ]
