# Generated by Django 2.0.5 on 2018-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0012_auto_20180611_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_files',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='cs_files'),
        ),
    ]
